# Server configuration
server.port=8080

# Spring application name
spring.application.name=gym-core

# Logging configuration
logging.level.org.springframework=INFO
logging.level.com.gymtracker=DEBUG

# Database configuration (update these values as needed)
spring.datasource.url=*********
spring.datasource.username=*******
spring.datasource.password=*******
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
